### PR TITLE
Simple tailwind UI

### PR DESCRIPTION
**Pull request by INSIDERDAVIDLAI**
Implemented Simple UI for QR Code Generator and URL Shortner, Using React as Framework and Tailwind CSS for UI

### CODE REVIEW

**Comment by LeonYanc** [comment]
For UI, it is mandatory to have screen shot, otherwise no PR approval will be granted

**Comment by INSIDERDAVIDLAI** [comment]
Hello

I believe there is one screenshot under my-react-app/screenshots which
demonstrate my simple UI

Thanks

Sincerely
David Lai

**Comment by LeonYanc** [comment]
Screen shot is what you manually take when you run the UI. if you don;t know how to do it in your windows/mac,  pls just google it

**Comment by INSIDERDAVIDLAI** [comment]
Hello Leon

Yes, I manually take a screenshot when I run the UI, and I placed
screenshot under my-react-app/screenshots, here is the screenshot of
location of my screenshot I just took.
[image: image.png]
Sincerely
David Lai



LeonYanc ***@***.***> 于2024年8月26日周一 13:01写道：

**Comment by LeonYanc** [comment]
The screen shots can be put in here as a comment. We don't want them to be persist in the code base

**Comment by INSIDERDAVIDLAI** [comment]
屏幕截图 2024-08-26 100601

**Review by LeonYanc — APPROVED** [review]

**Pull request merged**
